version: "2"
services:
  genial-mysql:
    container_name: genial-mysql
    build: .
    expose:
      - "3306"
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=genial
      - MYSQL_DATABASE=genial
      - MYSQL_USER=genial
      - MYSQL_PASSWORD=genial
    volumes:
      - ./volume/mysql:/var/lib/mysql
      - ./volume/data:/var/data
networks:
  genial:
    external: true
    name: genial
