version: "2"
services:
  inside-mysql:
    container_name: inside-mysql
    build: .
    expose:
      - "3306"
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=inside
      - MYSQL_DATABASE=inside
      - MYSQL_USER=inside
      - MYSQL_PASSWORD=inside
    volumes:
      - ./volume/mysql:/var/lib/mysql
      - ./volume/data:/var/data
networks:
  inside:
    external: true
    name: inside
